---
identifier: "CVE-2020-8563"
package_slug: "go/k8s.io/kubernetes/pkg/apis/apps/validation"
title: "Inclusion of Sensitive Information in Log Files"
description: "In Kubernetes clusters using VSphere as a cloud provider, with a logging
  level set to 4 or above, VSphere cloud credentials will be leaked in the cloud controller
  manager's log. This affects < v1.19.3."
date: "2021-03-29"
pubdate: "2020-12-07"
affected_range: "<1.19.3"
fixed_versions: []
affected_versions: "All versions before 1.19.3"
not_impacted: ""
solution: "Unfortunately, there is no solution available yet."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2020-8563"
cvss_v2: "AV:L/AC:L/Au:N/C:P/I:N/A:N"
cvss_v3: "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:N"
uuid: "baf85d13-20e0-4673-a28b-2a212b7a1fb2"
