---
identifier: "CVE-2021-25736"
identifiers:
- "CVE-2021-25736"
package_slug: "go/k8s.io/kubernetes/pkg/apis/apps/validation"
title: "TODO: Add proper title"
description: "Kube-proxy\n on Windows can unintentionally forward traffic to local
  processes \nlistening on the same port (“spec.ports[*].port”) as a LoadBalancer
  \nService when the LoadBalancer controller\n does not set the “status.loadBalancer.ingress[].ip”
  field. Clusters \nwhere the LoadBalancer controller sets the \n“status.loadBalancer.ingress[].ip”
  field are unaffected.\n\n"
date: "2023-11-16"
pubdate: "2023-10-30"
affected_range: ">=1.18.0 <1.18.18||>=1.19.0 <1.19.10||>=1.20.0 <1.20.6"
fixed_versions:
- "1.18.18"
- "1.19.10"
- "1.20.6"
affected_versions: "All versions starting from 1.18.0 before 1.18.18, all versions
  starting from 1.19.0 before 1.19.10, all versions starting from 1.20.0 before 1.20.6"
not_impacted: ""
solution: "Upgrade to versions 1.18.18, 1.19.10, 1.20.6 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2021-25736"
- "https://github.com/kubernetes/kubernetes/pull/99958"
- "https://groups.google.com/g/kubernetes-security-announce/c/lIoOPObO51Q/m/O15LOazPAgAJ"
cvss_v3: "CVSS:3.1/AV:N/AC:H/PR:L/UI:N/S:C/C:H/I:N/A:N"
uuid: "1b160b1f-da73-4a9b-a223-ca651e6fc5d5"
cwe_ids:
- "CWE-1035"
- "CWE-937"
