---
identifier: "CVE-2021-3532"
package_slug: "pypi/ansible"
title: "Information Exposure"
description: "A flaw was found in Ansible where the secret information present in
  async_files are getting disclosed when the user changes the jobdir to a world readable
  directory. Any secret information in an async status file will be readable by a
  malicious user on that system. This flaw affects Ansible Tower and Ansible Automation
  Platform "
date: "2021-06-21"
pubdate: "2021-06-09"
affected_range: "==2.0"
fixed_versions:
- "2.0.0.1"
affected_versions: "Version 2.0"
not_impacted: "All versions before 2.0, all versions after 2.0"
solution: "Upgrade to version 2.0.0.1 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2021-3532"
- "https://bugzilla.redhat.com/show_bug.cgi?id=1956464"
cvss_v2: "AV:N/AC:M/Au:N/C:P/I:N/A:N"
cvss_v3: "CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:H/I:N/A:N"
uuid: "06b67da0-8b7b-4490-aa3c-d0c9a2fe1787"
