source_identifier: CVE-2018-16876
title: Information Exposure
description: ansible is vulnerable to a information disclosure flaw in vvv+ mode with
  no_log on that can lead to leakage of sensible data.
date: "2018-12-07"
affected_range: '<2.5.14 || >=2.6.0.dev0, <2.6.11 || >=2.7.0.dev0, <2.7.5'
fixed_versions:
- 2.5.14
- 2.6.11
- 2.7.5
affected_versions: 'All versions before 2.5.14, all versions starting from 2.6.0.dev0
  before 2.6.11, all versions starting from 2.7.0.dev0 before 2.7.5'
solution: Upgrade to fixed version.
urls:
- http://www.securityfocus.com/bid/106225
- https://access.redhat.com/errata/RHSA-2018:3835
- https://access.redhat.com/errata/RHSA-2018:3836
- https://access.redhat.com/errata/RHSA-2018:3837
- https://access.redhat.com/errata/RHSA-2018:3838
- https://access.redhat.com/errata/RHSA-2019:0564
- https://access.redhat.com/errata/RHSA-2019:0590
- https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-16876
- https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2018-16876
- https://cwe.mitre.org/data/definitions/200.html
- https://github.com/ansible/ansible/pull/49569
- https://www.debian.org/security/2019/dsa-4396
uuid: 6a4542fc-7a40-4981-879b-0555dfa6db9c
package_slug: pypi/ansible
