stages:
  - test
  - deploy

missing_uuids:
  image: golang:1.11
  script:
    - go run missing_uuids/main.go .

test:
  image: ruby:2.6-alpine3.10
  script:
    # TODO perhaps this should be a submodule?
    - git clone "https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/gitlab-org/security-products/advisory-db-curation-tools.git"
    - bundle install --gemfile advisory-db-curation-tools/adbcurate/Gemfile
    - bundle install --gemfile schema/Gemfile
    - bundle install --gemfile identifier/Gemfile
    - schema/validate.rb --semantic gem go npm maven packagist pypi
    - identifier/identifier.rb -v .

pages:
  image: julianthome/stat
  stage: deploy
  script:
    - cd stats && make
  artifacts:
    paths:
      - data/data.tar.gz
      - data/nvd.tar.gz
      - public
  allow_failure: true
  only:
    - master
