stages:
  - test

missing_uuids:
  image: golang:1.11
  script:
    - go run missing_uuids/main.go .

test:
  image: ruby:2.6-alpine3.10
  script:
    - cd schema && bundle install
    - ruby validate.rb
