# You can override the included template(s) by including variable overrides
# See https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#priority-of-environment-variables
stages:
- test
- bump
- deploy
default:
  tags:
  - gitlab-org
workflow:
  rules:
  - if: "$CI_MERGE_REQUEST_IID"
  - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
  - if: "$CI_COMMIT_TAG"
syntax:
  image: python:3
  stage: test
  before_script:
  - pip install yamllint
  script:
  - yamllint .
  resource_group: gemnasium-db
semantic:
  image: ruby:2.6-alpine3.10
  stage: test
  before_script:
  - apk add git openssh-client
  - mkdir -p ~/.ssh && chmod 700 ~/.ssh
  - ssh-keyscan gitlab.com >> ~/.ssh/known_hosts && chmod 644 ~/.ssh/known_hosts
  - eval $(ssh-agent -s)
  - echo "$SEMVER_DIALECT_SSH" | tr -d '\r' | ssh-add -
  script:
  - bundle install --gemfile schema/Gemfile
  - bundle install --gemfile identifier/Gemfile
  - bundle exec --gemfile schema/Gemfile schema/validate.rb --semantic gem go npm
    maven packagist pypi conan nuget
  - identifier/identifier.rb -v .
  resource_group: gemnasium-db
bump:
  image: registry.gitlab.com/gitlab-org/secure/vulnerability-research/workflow-tools/bumper:master-v1.0.0
  stage: bump
  rules:
  - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
  variables:
    GIT_STRATEGY: none
  before_script:
  - mkdir -p ~/.ssh && chmod 700 ~/.ssh
  - ssh-keyscan gitlab.com >> ~/.ssh/known_hosts && chmod 644 ~/.ssh/known_hosts
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$BUMPER_SSH")
  - git clone git@gitlab.com:gitlab-org/security-products/gemnasium-db.git
  script:
  - bump.rb -v "v" -c "CHANGELOG.md" -g "gemnasium-db" -n "bumper" -e "bumper@gitlab.com"
  resource_group: gemnasium-db
pages:
  image: julianthome/stat
  stage: deploy
  rules:
  - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
  - if: "$CI_COMMIT_TAG"
  script:
  - cd stats && make
  resource_group: gemnasium-db
  artifacts:
    paths:
    - data/data.tar.gz
    - data/nvd.tar.gz
    - public
sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml
