---
identifier: "CVE-2021-25737"
package_slug: "go/github.com/kubernetes/kubernetes"
title: "URL Redirection to Untrusted Site (Open Redirect)"
description: "A security issue was discovered in Kubernetes where a user may be able
  to redirect pod traffic to private networks on a Node. Kubernetes already prevents
  creation of Endpoint IPs in the localhost or link-local range, but the same validation
  was not performed on EndpointSlice IPs."
date: "2021-09-13"
pubdate: "2021-09-06"
affected_range: ">=v1.16.0 <v1.18.19 || >=v1.19.0 <v1.19.10 || >=v1.20.0 <v1.20.7
  || =v1.21.0"
fixed_versions:
- "v1.18.19"
- "v1.19.10"
- "v1.20.7"
- "v1.21.1-rc.0"
affected_versions: "All versions starting from 1.16.0 before 1.18.19, all versions
  starting from 1.19.0 before 1.19.10, all versions starting from 1.20.0 before 1.20.7,
  version 1.21.0"
not_impacted: "All versions before 1.16.0, all versions starting from 1.18.19 before
  1.19.0, all versions starting from 1.19.10 before 1.20.0, all versions starting
  from 1.20.7 before 1.21.0, all versions after 1.21.0"
solution: "Upgrade to versions 1.18.19, 1.19.10, 1.20.7, 1.21.1-rc.0 or above. *Note*:
  1.21.1-rc.0 may be an unstable version. Use caution."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2021-25737"
cvss_v2: "AV:N/AC:M/Au:S/C:P/I:P/A:N"
cvss_v3: "CVSS:3.1/AV:N/AC:L/PR:H/UI:R/S:C/C:L/I:L/A:N"
uuid: "6c9d6632-c0d5-4cc2-89f4-5c3ba372260d"
versions:
- number: "v1.16.0"
  commit:
    tags:
    - "v1.16.0"
    sha: "38d05c7c415152c9249ad0c553cbbcb86f247a68"
    timestamp: "20190913145653"
- number: "v1.19.0"
  commit:
    tags:
    - "v1.19.0"
    sha: "0fc1dcd829d621ec5605d3eeb381e728371da832"
    timestamp: "20200826142205"
- number: "v1.20.0"
  commit:
    tags:
    - "v1.20.0"
    sha: "1833d7d52ad70d4a740796ee2dc6c1eb47666b81"
    timestamp: "20201204214525"
- number: "v1.21.1-rc.0"
  commit:
    tags:
    - "v1.21.1-rc.0"
    sha: "70c290b8e13a69bf31b34c53609a01e2ab2068e3"
    timestamp: "20210408162405"
- number: "v1.21.0"
  commit:
    tags:
    - "v1.21.0"
    sha: "1bbafafc371fc63412cac3ad955ed80c42a22b88"
    timestamp: "20210408162405"
- number: "v1.19.10"
  commit:
    tags:
    - "v1.19.10"
    sha: "62ceda52b4dd04529266abdeaaffeb73e79c4a39"
    timestamp: "20210415031931"
- number: "v1.18.19"
  commit:
    tags:
    - "v1.18.19"
    sha: "eedd6105b606eb7f2ff082df9c2b5300f32a07cd"
    timestamp: "20210512112113"
- number: "v1.20.7"
  commit:
    tags:
    - "v1.20.7"
    sha: "4465f227a413d9e5d3d7c36e7e569cbbe785dcf5"
    timestamp: "20210512123156"
