---
identifier: "CVE-2021-25740"
package_slug: "go/github.com/kubernetes/kubernetes"
title: "Externally Controlled Reference to a Resource in Another Sphere"
description: "A security issue was discovered with Kubernetes that could enable users
  to send network traffic to locations they would otherwise not have access to via
  a confused deputy attack."
date: "2021-10-01"
pubdate: "2021-09-20"
affected_range: ""
fixed_versions: []
affected_versions: "All versions"
not_impacted: ""
solution: "Unfortunately, there is no solution available yet."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2021-25740"
cvss_v2: "AV:N/AC:M/Au:S/C:P/I:N/A:N"
cvss_v3: "CVSS:3.1/AV:N/AC:H/PR:L/UI:N/S:U/C:L/I:N/A:N"
uuid: "7626605e-66c0-453e-b665-f1cef4e74d77"
versions: []
