---
identifier: "CVE-2021-25741"
package_slug: "go/github.com/kubernetes/client-go"
title: "Files or Directories Accessible to External Parties"
description: "A security issue was discovered in Kubernetes where a user may be able
  to create a container with subpath volume mounts to access files & directories outside
  of the volume, including on the host filesystem."
date: "2021-10-08"
pubdate: "2021-09-20"
affected_range: "<=1.19.14||>=1.20.0 <=1.20.10||>=1.21.0 <=1.21.4||>=1.22.0 <=1.22.1"
fixed_versions:
- "0.15.7"
affected_versions: "All versions up to 1.19.14, all versions starting from 1.20.0
  up to 1.20.10, all versions starting from 1.21.0 up to 1.21.4, all versions starting
  from 1.22.0 up to 1.22.1"
not_impacted: "All versions after 1.19.14 before 1.20.0, all versions after 1.20.10
  before 1.21.0, all versions after 1.21.4 before 1.22.0, all versions after 1.22.1"
solution: "Upgrade to version 0.15.7 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2021-25741"
cvss_v2: "AV:N/AC:L/Au:S/C:P/I:P/A:N"
cvss_v3: "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:N"
uuid: "0d53493c-f026-4d9e-aa90-d16ff8f78e9b"
