---
identifier: "GMS-2022-8053"
identifiers:
- "GHSA-468w-8x39-gj5v"
- "GMS-2022-8053"
- "CVE-2022-46153"
package_slug: "go/github.com/traefik/traefik/v2"
title: "Traefik routes exposed with an empty TLSOption"
description: "## Impact\n\nThere is a potential vulnerability in Traefik managing
  the TLS connections.\n\nA router configured with a not well-formatted [TLSOption](https://doc.traefik.io/traefik/v2.9/https/tls/#tls-options)
  is exposed with an empty TLSOption.\n\nFor instance, a route secured using an mTLS
  connection set with a wrong CA file is exposed without verifying the client certificates.\n\n##
  Patches\n\nhttps://github.com/traefik/traefik/releases/tag/v2.9.6\n\n## Workarounds\n\nCheck
  the logs to detect the following error messages and fix your TLS options:\n\n- Empty
  CA:\n\n```\n{\"level\":\"error\",\"msg\":\"invalid clientAuthType: RequireAndVerifyClientCert,
  CAFiles is required\",\"routerName\":\"Router0@file\"}\n```\n\n- Bad CA content
  (or bad path):\n\n```\n{\"level\":\"error\",\"msg\":\"invalid certificate(s) content\",\"routerName\":\"Router0@file\"}\n```\n\n-
  Unknown Client Auth Type:\n\n```\n{\"level\":\"error\",\"msg\":\"unknown client
  auth type \\\"FooClientAuthType\\\"\",\"routerName\":\"Router0@file\"}\n```\n\n-
  Invalid cipherSuites\n\n```\n{\"level\":\"error\",\"msg\":\"invalid CipherSuite:
  foobar\",\"routerName\":\"Router0@file\"}\n```\n\n- Invalid curvePreferences\n\n```\n{\"level\":\"error\",\"msg\":\"invalid
  CurveID in curvePreferences: foobar\",\"routerName\":\"Router0@file\"}\n``` \n\n##
  For more information\n\nIf you have any questions or comments about this advisory,
  please [open an issue](https://github.com/traefik/traefik/issues)."
date: "2022-12-08"
pubdate: "2022-12-08"
affected_range: "<v2.9.6"
fixed_versions:
- "v2.9.6"
affected_versions: "All versions before 2.9.6"
not_impacted: "All versions starting from 2.9.6"
solution: "Upgrade to version 2.9.6 or above."
urls:
- "https://github.com/traefik/traefik/security/advisories/GHSA-468w-8x39-gj5v"
- "https://doc.traefik.io/traefik/v2.9/https/tls/#tls-options"
- "https://github.com/traefik/traefik/releases/tag/v2.9.6"
- "https://github.com/advisories/GHSA-468w-8x39-gj5v"
uuid: "bc140cda-c19b-487b-a7a3-c98f9590a39c"
cwe_ids:
- "CWE-1035"
- "CWE-937"
versions:
- number: "v2.9.6"
  commit:
    tags:
    - "v2.9.6"
    sha: "d97d3a6726ad6e50110dd2ff2b552a8b17eeed55"
    timestamp: "20221207141405"
