---
identifier: "CVE-2021-3162"
package_slug: "go/github.com/docker/libcontainer"
title: "Improper Privilege Management"
description: "Docker Desktop Community on macOS mishandles certificate checking, leading
  to local privilege escalation."
date: "2021-01-22"
pubdate: "2021-01-15"
affected_range: "<v2.5.0.0"
fixed_versions: []
affected_versions: "All versions before 2.5.0.0"
not_impacted: ""
solution: "Unfortunately, there is no solution available yet."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2021-3162"
- "https://docs.docker.com/docker-for-mac/release-notes/#docker-desktop-community-2500"
cvss_v2: "AV:L/AC:L/Au:N/C:P/I:P/A:P"
cvss_v3: "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H"
uuid: "a801d8b5-e497-4fc6-86ce-2046be0685e9"
versions: []
